backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://comunidadit.netlify.com

collections:
  - name: "pages"
    label: "Pages"
    delete: false
    create: false
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Cuerpo", name: "body", widget: "markdown"}

  - name: "material"
    label: "Material"
    folder: "src/pages/material"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "material"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Fecha", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "person"
    label: "Personas"
    folder: "src/data/persons"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "person"}
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Rol", name: "rol", widget: "string"}
      - {label: "Twitter", name: "twitter", widget: "string"}
      - {label: "Linkedin", name: "linkedin", widget: "string"}
      - {label: "Mail", name: "mail", widget: "string"}
      - {
        label: "Imagen de perfil",
        name: "imgSrc",
        widget: "image",
        media_library:
          {
            config:
              {
                multiple: false
              }
          }
      }
