backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://comunidadit.netlify.com

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Cuerpo", name: "body", widget: "markdown"}
