backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://comunidadit.netlify.com

collections:
  - name: "pages"
    label: "Pages"
    delete: false
    create: false
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Cuerpo", name: "body", widget: "markdown"}

  - name: "material"
    label: "Material"
    folder: "src/pages/material"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "material"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Fecha", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
